<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../HarmonicaScript.Core/HarmonicaScript.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MeltySynth" />
    <PackageReference Include="Microsoft.CodeAnalysis.BannedApiAnalyzers" PrivateAssets="all" />
    <AdditionalFiles Include="BannedSymbols.txt" />
  </ItemGroup>
</Project>
