using System.Globalization;
using System.Text;
using HarmonicaScript.Core.Instrument;
using HarmonicaScript.Core.Timeline;

namespace HarmonicaScript.Export.Exporters;

/// <summary>
/// AutoHotkey v2. THE most important export in the project.
///
/// It reaches the game through an injection engine that thousands of people have already
/// validated, which makes it Branch A with the developer's unverifiable surface removed - and it
/// becomes possible the moment the timeline emitter works, which is why it ships before any of
/// our own Windows code exists.
/// </summary>
public sealed class AutoHotkeyV2Exporter : IMacroExporter
{
    public string Id => "ahk-v2";

    public LocalizedText DisplayName => new("AutoHotkey v2 script", "AutoHotkey v2 脚本");

    public string FileExtension => ".ahk";

    public ExporterCapabilities Capabilities { get; } = new(
        SupportsSeparateDownUp: true,
        SupportsMouse: true,
        TextEncoding: new UTF8Encoding(encoderShouldEmitUTF8Identifier: true),
        NewLine: "\r\n");

    public ExportResult Write(ExportContext context, Stream output)
    {
        ArgumentNullException.ThrowIfNull(context);
        ArgumentNullException.ThrowIfNull(output);

        var lowered = MacroLowering.Lower(context.Timeline, Capabilities);
        var nl = Capabilities.NewLine;
        var builder = new StringBuilder();

        builder.Append("#Requires AutoHotkey v2.0").Append(nl);
        builder.Append("#SingleInstance Force").Append(nl);
        builder.Append("SendMode(\"Input\")").Append(nl);
        builder.Append("SetKeyDelay(-1, -1)").Append(nl);
        builder.Append("SetMouseDelay(-1)").Append(nl).Append(nl);

        builder.Append("; Generated by HarmonicaScript. Do not edit by hand.").Append(nl);
        builder.Append("; Song      : ").Append(Sanitise(context.Meta.Title)).Append(nl);
        builder.Append("; Instrument: ").Append(context.Instrument.Ref).Append(nl);
        builder.Append("; Events    : ").Append(lowered.TotalEvents.ToString(CultureInfo.InvariantCulture)).Append(nl);
        builder.Append("; Duration  : ").Append((context.Timeline.TotalDurationMs / 1000.0).ToString("0.0", CultureInfo.InvariantCulture)).Append(" s").Append(nl);
        builder.Append(';').Append(nl);
        builder.Append("; F5 start / F6 stop. Everything is released on exit, including on a crash.").Append(nl);
        builder.Append("; The game must be in BORDERLESS WINDOWED mode and focused, with an English IME.").Append(nl).Append(nl);

        EmitPrologue(builder, nl);
        EmitReleaseAll(builder, context, nl);
        EmitPlayback(builder, context, lowered, nl);

        var bytes = Capabilities.Encoding.GetBytes(builder.ToString());
        output.Write(bytes, 0, bytes.Length);

        return new ExportResult(
            true,
            lowered.Warnings,
            [
                "把 .ahk 文件用 AutoHotkey v2 打开，切到游戏（无边框窗口模式），按 F5 开始、F6 停止。",
                "Open the .ahk with AutoHotkey v2, switch to the game in borderless-windowed mode, press F5 to start and F6 to stop.",
            ],
            []);
    }

    private static void EmitPrologue(StringBuilder builder, string nl)
    {
        // timeBeginPeriod(1) is per-process since Windows 10 2004, so a script that wants
        // millisecond sleeps has to ask for the resolution itself.
        builder.Append("global Running := false").Append(nl).Append(nl);
        builder.Append("DllCall(\"winmm\\timeBeginPeriod\", \"UInt\", 1)").Append(nl);
        builder.Append("OnExit(Cleanup)").Append(nl).Append(nl);

        builder.Append("Cleanup(*) {").Append(nl);
        builder.Append("    Running := false").Append(nl);
        builder.Append("    ReleaseAll()").Append(nl);
        builder.Append("    DllCall(\"winmm\\timeEndPeriod\", \"UInt\", 1)").Append(nl);
        builder.Append("    return 0").Append(nl);
        builder.Append('}').Append(nl).Append(nl);

        // Absolute scheduling against QueryPerformanceCounter. Sleeping a per-note delta
        // accumulates every rounding error; scheduling against a fixed origin cannot.
        builder.Append("Now() {").Append(nl);
        builder.Append("    static freq := 0").Append(nl);
        builder.Append("    if (freq = 0)").Append(nl);
        builder.Append("        DllCall(\"QueryPerformanceFrequency\", \"Int64*\", &freq)").Append(nl);
        builder.Append("    DllCall(\"QueryPerformanceCounter\", \"Int64*\", &c := 0)").Append(nl);
        builder.Append("    return c * 1000.0 / freq").Append(nl);
        builder.Append('}').Append(nl).Append(nl);

        builder.Append("WaitUntil(t0, targetMs) {").Append(nl);
        builder.Append("    loop {").Append(nl);
        builder.Append("        if (!Running)").Append(nl);
        builder.Append("            return false").Append(nl);
        builder.Append("        remaining := (t0 + targetMs) - Now()").Append(nl);
        builder.Append("        if (remaining <= 0.3)").Append(nl);
        builder.Append("            return true").Append(nl);
        builder.Append("        if (remaining > 3)").Append(nl);
        builder.Append("            Sleep(Round(remaining) - 2)").Append(nl);
        builder.Append("        else").Append(nl);
        builder.Append("            Sleep(-1)").Append(nl);
        builder.Append("    }").Append(nl);
        builder.Append('}').Append(nl).Append(nl);
    }

    private static void EmitReleaseAll(StringBuilder builder, ExportContext context, string nl)
    {
        builder.Append("ReleaseAll() {").Append(nl);

        foreach (var degree in context.Instrument.Degrees)
        {
            builder.Append("    Send(\"").Append(Token(context, degree.Binding, down: false)).Append("\")").Append(nl);
        }

        foreach (var modifier in context.Instrument.Modifiers)
        {
            builder.Append("    Send(\"").Append(Token(context, modifier.Binding, down: false)).Append("\")").Append(nl);
        }

        builder.Append('}').Append(nl).Append(nl);
    }

    private static void EmitPlayback(StringBuilder builder, ExportContext context, LoweredTimeline lowered, string nl)
    {
        builder.Append("F6::{").Append(nl);
        builder.Append("    Running := false").Append(nl);
        builder.Append("    ReleaseAll()").Append(nl);
        builder.Append('}').Append(nl).Append(nl);

        builder.Append("F5::{").Append(nl);
        builder.Append("    if (Running)").Append(nl);
        builder.Append("        return").Append(nl);
        builder.Append("    Running := true").Append(nl);
        builder.Append("    ReleaseAll()   ; recover from any previous hard stop").Append(nl);
        builder.Append("    t0 := Now()").Append(nl);

        foreach (var part in lowered.Parts)
        {
            var absoluteMs = 0;
            foreach (var e in part.Events)
            {
                absoluteMs += e.DelayBeforeMs;
                if (e.Event.NoteId == -2)
                {
                    continue;   // pure wait inserted by the long-delay splitter
                }

                builder.Append("    if (!WaitUntil(t0, ").Append(absoluteMs.ToString(CultureInfo.InvariantCulture))
                    .Append(")) {").Append(nl);
                builder.Append("        ReleaseAll()").Append(nl);
                builder.Append("        return").Append(nl);
                builder.Append("    }").Append(nl);

                var binding = new Binding(e.Event.Device, e.Event.Code);
                builder.Append("    Send(\"").Append(Token(context, binding, e.Event.IsDown)).Append("\")").Append(nl);
            }
        }

        builder.Append("    Running := false").Append(nl);
        builder.Append("    ReleaseAll()").Append(nl);
        builder.Append('}').Append(nl);
    }

    /// <summary>
    /// A Send token.
    ///
    /// <c>{Blind}</c> is MANDATORY and not a style choice: we hold a mouse modifier across many
    /// notes, and an un-blinded Send helpfully "restores" modifier state between calls, which
    /// would release the control we are deliberately holding. Scan codes rather than characters,
    /// because many games ignore virtual-key injection outright.
    /// </summary>
    private static string Token(ExportContext context, Binding binding, bool down)
    {
        var direction = down ? "down" : "up";

        if (binding.IsMouse)
        {
            var mouse = context.Keys.Mouse(binding.AsMouseButton);
            return $"{{Blind}}{{{mouse.Ahk} {direction}}}";
        }

        var key = context.Keys.Key(binding.Code);
        var scan = key.Extended ? $"sc{key.ScanCode1 + 0x100:X3}" : $"sc{key.ScanCode1:X3}";
        return $"{{Blind}}{{{scan} {direction}}}";
    }

    private static string Sanitise(string text) =>
        text.Replace("\r", " ", StringComparison.Ordinal).Replace("\n", " ", StringComparison.Ordinal);
}
