using System.Globalization;
using System.Text;
using HarmonicaScript.Core.Instrument;

namespace HarmonicaScript.Export.Exporters;

/// <summary>
/// Logitech, as a .lua script for the G HUB / LGS script editor (Script -> Import).
///
/// The primary Logitech deliverable, and deliberately NOT a profile JSON: G HUB has no
/// file-based macro import at all - macros live inside a settings database with per-machine
/// GUIDs - whereas the Lua editor's Import is a supported, documented UI path that covers both
/// G HUB and legacy LGS with one artifact.
///
/// The only vendor exporter that ships UNGATED, because it is the only one whose mouse encoding
/// is publicly documented rather than inferred from a sample.
/// </summary>
public sealed class LogitechLuaExporter : IMacroExporter
{
    public string Id => "logitech-lua";

    public LocalizedText DisplayName => new("Logitech G HUB / LGS script", "罗技 G HUB / LGS 脚本");

    public string FileExtension => ".lua";

    public ExporterCapabilities Capabilities { get; } = new(
        MinDelayMs: 1,
        SupportsSeparateDownUp: true,
        SupportsMouse: true,
        VerifiedMouseButtons: [MouseButton.Left, MouseButton.Middle, MouseButton.Right],
        TextEncoding: new UTF8Encoding(encoderShouldEmitUTF8Identifier: false),
        NewLine: "\r\n",
        Quirks: new Dictionary<string, int?>
        {
            // The documented trap: PressMouseButton numbers buttons 1=L 2=M 3=R, while the
            // OnEvent handler's arg uses 1=L 2=R 3=M. Getting these the same way round is a
            // classic Logitech scripting bug.
            ["pressMouseButton.left"] = 1,
            ["pressMouseButton.middle"] = 2,
            ["pressMouseButton.right"] = 3,
        });

    public ExportResult Write(ExportContext context, Stream output)
    {
        ArgumentNullException.ThrowIfNull(context);
        ArgumentNullException.ThrowIfNull(output);

        var lowered = MacroLowering.Lower(context.Timeline, Capabilities);
        var nl = Capabilities.NewLine;
        var builder = new StringBuilder();

        builder.Append("-- Generated by HarmonicaScript. Do not edit by hand.").Append(nl);
        builder.Append("-- Song      : ").Append(context.Meta.Title).Append(nl);
        builder.Append("-- Instrument: ").Append(context.Instrument.Ref).Append(nl);
        builder.Append("-- Events    : ").Append(lowered.TotalEvents.ToString(CultureInfo.InvariantCulture)).Append(nl);
        builder.Append("--").Append(nl);
        builder.Append("-- Import via the script editor: Script -> Import, then Save and Run.").Append(nl);
        builder.Append("-- Press G1 to play. Press it again, or switch profile, to stop and release everything.").Append(nl).Append(nl);

        builder.Append("local playing = false").Append(nl).Append(nl);

        builder.Append("local function releaseAll()").Append(nl);
        foreach (var degree in context.Instrument.Degrees)
        {
            builder.Append("  ReleaseKey(").Append(ScanCode(context, degree.Binding)).Append(')').Append(nl);
        }

        foreach (var modifier in context.Instrument.Modifiers.Where(m => m.Binding.IsMouse))
        {
            builder.Append("  ReleaseMouseButton(").Append(MouseNumber(modifier.Binding.AsMouseButton)).Append(')').Append(nl);
        }

        builder.Append("end").Append(nl).Append(nl);

        builder.Append("local function play()").Append(nl);
        builder.Append("  releaseAll()").Append(nl);

        foreach (var part in lowered.Parts)
        {
            foreach (var e in part.Events)
            {
                if (e.DelayBeforeMs > 0)
                {
                    builder.Append("  Sleep(").Append(e.DelayBeforeMs.ToString(CultureInfo.InvariantCulture)).Append(')').Append(nl);
                }

                if (e.Event.NoteId == -2)
                {
                    continue;
                }

                // Checked between notes so a runaway script can always be stopped.
                builder.Append("  if not playing then releaseAll() return end").Append(nl);

                var binding = new Binding(e.Event.Device, e.Event.Code);
                if (binding.IsMouse)
                {
                    builder.Append(e.Event.IsDown ? "  PressMouseButton(" : "  ReleaseMouseButton(")
                        .Append(MouseNumber(binding.AsMouseButton)).Append(')').Append(nl);
                }
                else
                {
                    builder.Append(e.Event.IsDown ? "  PressKey(" : "  ReleaseKey(")
                        .Append(ScanCode(context, binding)).Append(')').Append(nl);
                }
            }
        }

        builder.Append("  releaseAll()").Append(nl);
        builder.Append("  playing = false").Append(nl);
        builder.Append("end").Append(nl).Append(nl);

        builder.Append("function OnEvent(event, arg)").Append(nl);
        builder.Append("  if event == \"PROFILE_ACTIVATED\" then").Append(nl);
        builder.Append("    EnablePrimaryMouseButtonEvents(true)").Append(nl);
        builder.Append("  elseif event == \"PROFILE_DEACTIVATED\" then").Append(nl);
        builder.Append("    playing = false").Append(nl);
        builder.Append("    releaseAll()").Append(nl);
        builder.Append("  elseif event == \"G_PRESSED\" and arg == 1 then").Append(nl);
        builder.Append("    if playing then").Append(nl);
        builder.Append("      playing = false").Append(nl);
        builder.Append("      releaseAll()").Append(nl);
        builder.Append("    else").Append(nl);
        builder.Append("      playing = true").Append(nl);
        builder.Append("      play()").Append(nl);
        builder.Append("    end").Append(nl);
        builder.Append("  end").Append(nl);
        builder.Append("end").Append(nl);

        var bytes = Capabilities.Encoding.GetBytes(builder.ToString());
        output.Write(bytes, 0, bytes.Length);

        return new ExportResult(
            true,
            lowered.Warnings,
            [
                "G HUB / LGS -> 脚本编辑器 -> Script -> Import，选择这个 .lua，然后 Save and Run。按 G1 开始/停止。",
                "In G HUB or LGS open the script editor, Script -> Import this .lua, then Save and Run. G1 starts and stops.",
                "注意：本导出器的按键编码来自罗技公开文档，但「导入后能否在游戏里正常播放」未经实机验证。",
            ],
            []);
    }

    /// <summary>Numeric Set-1 scan codes, with the extended bit, rather than key-name strings: unambiguous and identical to the Razer column.</summary>
    private static string ScanCode(ExportContext context, Binding binding)
    {
        var key = context.Keys.Key(binding.Code);
        var code = key.Extended ? key.ScanCode1 + 0x100 : key.ScanCode1;
        return "0x" + code.ToString("X2", CultureInfo.InvariantCulture);
    }

    private static int MouseNumber(MouseButton button) => button switch
    {
        MouseButton.Left => 1,
        MouseButton.Middle => 2,
        MouseButton.Right => 3,
        _ => throw new NotSupportedException($"Logitech scripting has no number for {button}."),
    };
}
